# Generated by Django 5.1.3 on 2024-12-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('latest', '最新帖子'), ('life', '校园生活分享'), ('love', '表白墙'), ('sale', '出售'), ('buy', '求购'), ('qa', '解答墙')], default='life', max_length=20, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
