# Generated by Django 5.1.3 on 2024-12-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_category_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('life', '校园生活分享'), ('love', '表白墙'), ('sale', '出售'), ('buy', '求购'), ('qa', '解答墙')], default='life', max_length=20, verbose_name='分类'),
        ),
    ]
