# Generated by Django 5.1.3 on 2024-12-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('latest', '最新墙'), ('confession', '表白墙'), ('life', '校园生活分享'), ('sale', '出售墙'), ('buy', '求购墙'), ('qa', '解答墙')], default='latest', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
